name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: taravel_docker
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, bcmath, curl
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-scripts --no-interaction
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Copy .env.example to .env
      run: cp .env.example .env
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Generate application key
      run: php artisan key:generate
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Set environment variables
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=taravel_docker" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Run Linter
      run: composer run-script lint
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Run Tests
      run: php artisan test
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst

    - name: Run CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff
      working-directory: ./src  # Hier wird das Arbeitsverzeichnis angepasst
